language: c
dist: trusty
sudo: required
script:
  - cmake -DNO_SYSTEMD_SUPPORT=1 .
  - make
  - make test


addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - protobuf-c-compiler
      - libprotobuf-c0-dev
      - check
